---@class Item
---@field id number
---@field name string
---@field displayName string 
---@field locDisplayName string
---@field displayNameWithSize string 
---@field locDisplayNameWithSize string 
---@field description string
---@field locDescription string
---@field type string
---@field unitMass number
---@field unitVolume number
---@field tier number
---@field scale string
---@field iconPath string
---@field schematics number[]
---@field products ItemQuantity[]